CREATE TABLE IF NOT EXISTS `contest` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `title` VARCHAR(200) NOT NULL COMMENT 'contest title',
    `encrypt` int NOT NULL DEFAULT 0 COMMENT '1: public 2: private 3: password',
    `start_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '比赛开始时间',
    `end_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '比赛结束时间',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;